services:
  - type: web
    name: ai-chat-backend
    env: ruby
    plan: free
    rootDir: backend
    buildCommand: bundle install && bundle exec rails db:migrate
    startCommand: bundle exec rails server -p $PORT -e production
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: 'true'