services:
  - type: web
    name: ai-chat-backend
    runtime: ruby
    plan: free
    rootDir: backend
    buildCommand: bundle install && bundle exec rails db:create db:migrate
    startCommand: bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: 'true'